sqs2sf:
  handler: index.sqs2sfHandler
  timeout: 200
  memory: 128
  source: 'node_modules/@cumulus/api/dist/sfStarter/'
  launchInVpc: true

sqs2sfThrottle:
  handler: index.sqs2sfThrottleHandler
  timeout: 200
  memory: 128
  source: 'node_modules/@cumulus/api/dist/sfStarter/'
  launchInVpc: true
  tables:
    - SemaphoresTable

log2elasticsearch:
  handler: index.logHandler
  timeout: 100
  memory: 320
  useElasticSearch: '{{es.name}}'
  launchInVpc: true
  source: 'node_modules/@cumulus/api/dist/indexer/'
  namedLambdaDeadLetterQueue: true

dbIndexer:
  handler: index.handler
  timeout: 300
  memory: 320
  source: 'node_modules/@cumulus/api/dist/dbIndexer/'
  useElasticSearch: '{{es.name}}'
  tables:
    - FilesTable
  launchInVpc: true
  envs:
    system_bucket: '{{system_bucket}}'
  namedLambdaDeadLetterQueue: true

fallbackConsumer:
  handler: index.handler
  timeout: 100
  memory: 256
  source: 'node_modules/@cumulus/api/dist/messageConsumer/'
  deadletterqueue: kinesisFailure
  launchInVpc: true
  tables:
    - RulesTable
    - CollectionsTable
    - ProvidersTable
  envs:
    system_bucket: '{{system_bucket}}'

cleanExecutions:
  handler: index.handler
  timeout: 900
  memory: 192
  source: 'node_modules/@cumulus/api/dist/cleanExecutions/'
  namedLambdaDeadLetterQueue: true
  launchInVpc: true
  tables:
    - ExecutionsTable
  envs:
    nonCompleteExecutionPayloadTimeout: '"{{non_complete_execution_payload_timeout}}"'
    completeExecutionPayloadTimeout: '"{{complete_execution_payload_timeout}}"'
    nonCompleteExecutionPayloadTimeoutDisable: '"{{non_complete_execution_payload_disable}}"'
    completeExecutionPayloadTimeoutDisable: '"{{complete_execution_payload_disable}}"'

# used as custom resource for cloudformation manipulation
CustomBootstrap:
  handler: index.handler
  timeout: 300
  memory: 320
  source: 'node_modules/@cumulus/api/dist/bootstrap/'
  launchInVpc: true
  envs:
    system_bucket: '{{system_bucket}}'

EmsIngestReport:
  handler: index.handler
  timeout: 300
  memory: 320
  source: 'node_modules/@cumulus/api/dist/emsIngestReport/'
  useElasticSearch: '{{es.name}}'
  launchInVpc: true
  tables:
    - CollectionsTable
  envs:
    system_bucket: '{{system_bucket}}'
    ems_provider: '{{ems.provider}}'
    ems_username: '{{ems.username}}'
    ems_privateKey: '{{ems.privateKey}}'
    ems_host: '{{ems.host}}'
    ems_port: '{{ems.port}}'
    ems_path: '{{ems.path}}'
    ems_dataSource: '{{ems.dataSource}}'
    ems_submitReport: '{{ems.submitReport}}'
    ems_retentionInDays: '{{ems.retentionInDays}}'
  namedLambdaDeadLetterQueue: true

EmsDistributionReport:
  handler: index.handler
  timeout: 900
  memory: 320
  source: 'node_modules/@cumulus/api/dist/emsDistributionReport/'
  launchInVpc: true
  tables:
    - CollectionsTable
    - GranulesTable
    - FilesTable
  envs:
    system_bucket: '{{system_bucket}}'
    ems_provider: '{{ems.provider}}'
    ems_username: '{{ems.username}}'
    ems_privateKey: '{{ems.privateKey}}'
    ems_host: '{{ems.host}}'
    ems_port: '{{ems.port}}'
    ems_path: '{{ems.path}}'
    ems_dataSource: '{{ems.dataSource}}'
    ems_submitReport: '{{ems.submitReport}}'
    ems_retentionInDays: '{{ems.retentionInDays}}'

EmsProductMetadataReport:
  handler: index.handler
  timeout: 300
  memory: 320
  source: 'node_modules/@cumulus/api/dist/emsProductMetadataReport/'
  launchInVpc: true
  tables:
    - CollectionsTable
  envs:
    system_bucket: '{{system_bucket}}'
    cmr_provider: '{{cmr.provider}}'
    cmr_client_id: '{{cmr.clientId}}'
    ems_provider: '{{ems.provider}}'
    ems_username: '{{ems.username}}'
    ems_privateKey: '{{ems.privateKey}}'
    ems_host: '{{ems.host}}'
    ems_port: '{{ems.port}}'
    ems_path: '{{ems.path}}'
    ems_dataSource: '{{ems.dataSource}}'
    ems_submitReport: '{{ems.submitReport}}'
    ems_retentionInDays: '{{ems.retentionInDays}}'

executeMigrations:
  handler: index.handler
  timeout: 300
  useElasticSearch: '{{es.name}}'
  memory: 1024
  source: 'node_modules/@cumulus/api/dist/executeMigrations/'
  launchInVpc: true
  tables:
    - GranulesTable
    - FilesTable
    - ExecutionsTable
    - PdrsTable
    - RulesTable
  envs:
    KinesisInboundEventLogger:
      function: Ref
      value: KinesisInboundEventLoggerLambdaFunction
    system_bucket: '{{system_bucket}}'

messageConsumer:
  handler: index.handler
  timeout: 100
  memory: 256
  source: 'node_modules/@cumulus/api/dist/messageConsumer/'
  launchInVpc: true
  tables:
    - RulesTable
    - CollectionsTable
    - ProvidersTable
  envs:
    system_bucket: '{{system_bucket}}'
    FallbackTopicArn:
      function: Fn::Sub
      value: '${kinesisFallbackSns}'

CreateReconciliationReport:
  handler: index.handler
  source: 'node_modules/@cumulus/api/dist/createReconciliationReport/'
  launchInVpc: true
  memory: 256
  useDistributionApi: true
  tables:
    - CollectionsTable
    - GranulesTable
    - FilesTable
  envs:
    system_bucket: '{{system_bucket}}'
    cmr_provider: '{{cmr.provider}}'
    cmr_client_id: '{{cmr.clientId}}'
    CMR_LIMIT: '{{cmr.cmrLimit}}'
    CMR_PAGE_SIZE: '{{cmr.cmrPageSize}}'

ScheduleSF:
  description: 'This lambda function is invoked by scheduled rules created via cumulus API'
  handler: index.schedule
  timeout: 100
  memory: 192
  source: 'node_modules/@cumulus/api/dist/sfScheduler/'
  launchInVpc: true
  tables:
    - CollectionsTable
    - ProvidersTable
  envs:
    system_bucket: '{{system_bucket}}'
  namedLambdaDeadLetterQueue: true

BulkDelete:
  handler: index.handler
  source: 'node_modules/@cumulus/api/dist/bulkDelete/'
  launchInVpc: true

KinesisInboundEventLogger:
  handler: index.handler
  timeout: 300
  memory: 128
  source: 'node_modules/@cumulus/api/dist/payloadLogger/'
  launchInVpc: true

KinesisOutboundEventLogger:
  handler: index.handler
  timeout: 300
  memory: 512
  source: 'node_modules/@cumulus/api/dist/payloadLogger/'
  launchInVpc: true

sfSemaphoreDown:
  handler: index.handler
  timeout: 100
  memory: 512
  source: 'node_modules/@cumulus/api/dist/sfSemaphoreDown/'
  launchInVpc: true
  tables:
    - SemaphoresTable

IndexFromDatabase:
  handler: index.handler
  timeout: 300
  memory: 512
  source: 'node_modules/@cumulus/api/dist/indexFromDatabase/'
  launchInVpc: true
  useElasticSearch: '{{es.name}}'

reportExecutions:
  handler: index.handler
  timeout: 30
  memory: 128
  source: 'node_modules/@cumulus/api/dist/reportExecutions/'
  launchInVpc: true
  tables:
    - ExecutionsTable

reportGranules:
  handler: index.handler
  timeout: 30
  memory: 256
  source: 'node_modules/@cumulus/api/dist/reportGranules/'
  launchInVpc: true
  tables:
    - GranulesTable

reportPdrs:
  handler: index.handler
  timeout: 30
  memory: 128
  source: 'node_modules/@cumulus/api/dist/reportPdrs/'
  launchInVpc: true
  tables:
    - PdrsTable

BulkOperation:
  handler: index.handler
  timeout: 300
  memory: 512
  source: 'node_modules/@cumulus/api/dist/bulkOperation/'
  launchInVpc: true
  tables:
    - GranulesTable
  envs:
    system_bucket: '{{system_bucket}}'
    METRICS_ES_HOST: '{{METRICS_ES_HOST}}'
    METRICS_ES_USER: '{{METRICS_ES_USER}}'
    METRICS_ES_PASS: '{{METRICS_ES_PASS}}'

sqsMessageConsumer:
  handler: index.handler
  timeout: 100
  memory: 256
  source: 'node_modules/@cumulus/api/dist/sqsMessageConsumer/'
  launchInVpc: true
  tables:
    - RulesTable
    - CollectionsTable
    - ProvidersTable
  envs:
    system_bucket: '{{system_bucket}}'
